export const SET_REPORT_NOTIFICATION = "SET_REPORT_NOTIFICATION";
export const SET_CONTENT_ISDRAFT_STATE = "SET_CONTENT_ISDRAFT_STATE";
export const SET_INDEFINITE_PROGRESS_STATE = "SET_INDEFINITE_PROGRESS_STATE";
export const SET_PAGE_HANDSHAKE_PROGRESS = "SET_PAGE_HANDSHAKE_PROGRESS";
